import string

from DroppyAnalyzer.types.keywords import MODULES

SPACE_TOKEN = " \t"
ASCII_TOKEN = string.ascii_letters
DIGITS_TOKEN = '0123456789'
IDENTIFIERS_SET = f"{ASCII_TOKEN}{DIGITS_TOKEN}_"

INT_TOKEN = "INT"
FLOAT_TOKEN = "FLOAT"
STRING_TOKEN = "STRING"
KEYWORDS_TOKEN = "KEYWORDS"
IDENTIFIER_TOKEN = "IDENTIFIER"
OPERATOR_TOKEN = "OPERATOR"
ARITHMETIC_OPERATOR_TOKEN = "ARITHMETIC_OPERATOR"
BITWISE_OPERATORS_TOKEN = "BITWISE_OPERATORS"
RELATIONAL_OPERATOR_TOKEN = "RELATIONAL_OPERATOR"
LOGICAL_OPERATORS_TOKEN = "LOGICAL_OPERATORS"
COMMENTS_TOKEN = "COMMENTS_TOKEN"
MODULES_TOKEN = "MODULES_TOKEN"

COMMENTS_STARTS_WITH = ["//" , "/*"]
COMMENTS_ENDS_WITH = ["*/"]
HARDCODED_STRINGS = ["\"" , "'"]
