import string


SPACE_TOKEN = " \t"
ASCII_TOKEN = string.ascii_letters
DIGITS_TOKEN = '0123456789'
IDENTIFIERS_SET = f"{ASCII_TOKEN}{DIGITS_TOKEN}_"

INT_TOKEN = "INT"
FLOAT_TOKEN = "FLOAT"
KEYWORDS_TOKEN = "KEYWORDS"
IDENTIFIER_TOKEN = "IDENTIFIER"
OPERATOR_TOKEN = "OPERATOR"